### PR TITLE
feat: Extensions/Projects page on the Gate Website

### PR DESCRIPTION
**Pull request by dilllxd**
This PR adds an Extensions/Projects page to the Gate Website. This would allow users to add their own Plugins/Extensions for Gate to the Gate website by adding the topic gate-extension to their repo! This also allows users to see what projects are importing Minekube Libraries in their go.mod file.

All API work is done through Cloudflare Pages functions, and we currently cache all repo's locally in browser and also a KV in Cloudflare to stay within GitHub's API and Cloudflare's limits.

I still have some small things to change (like the url title) but this is technically ready to merge whenever it has been checked over and the required changes to the Cloudflare Pages deployment settings have been added. Sorry for the low commits btw, most of the work was done locally :)

Pictures:

Extension Page
Minekube Libraries Page

### CODE REVIEW

**Comment by dilllxd** [comment]
I just pushed the feature to automatically update the webpage title based on what search mode is being used so technically I think the current wanted features are done. I also wanted to see opinions on if it should be added to the homepage with a button next to quick start and a new nav link on the header. I attached a picture showing how it looks currently with it added to both places. 
Plus, I'm not exactly sure what we should label it as. Extensions made sense at first as it was only originally going to be Gate extensions but it's now been expanded to projects that import go.minekube.com so I'm not sure what it should be named lmk your opinions on that as well :)

image

**Comment by dilllxd** [comment]
Added the ability to show cached data stored in the browsers localstorage if the api is unreachable for some reason. Here's pictures of what is shown for each type of situation (1. cached data, but api is unreachable 2. no cached data and api is unreachable)

number 1
number 2

**Comment by oglassdev** [comment]
bro took a small amount of inspiration from the minestom website

**Comment by dilllxd** [comment]
> bro took a small amount of inspiration from the minestom website

@oglassdev Haha yeah, their page fit really well with what I wanted so I tried to remake it. This was my first time using vitepress so it helped to have something to bounce off of when working on it. I want to try and experiment with other designs soon though and see if anything would work better since the Minekube Repositories page might get cluttered as the libraries get used more and more. If you have any ideas feel free to lmk and I’ll try and work on them (:

**Comment by robinbraemer** [comment]
Exciting! It is much better than the initial requirements!

**Review by robinbraemer — APPROVED** [review]
Looking good!


minor future improvements:

- ui: make the search consider both the repo description in addition to the name
- ui: display the two search modes switches to visible
- code: extract duplicate code into a shared js file imported by both extensions.js and go-modules.js

**Pull request merged**
