### PR TITLE
add method to send new commands to player

### PR DESCRIPTION
**Pull request by gmax79**

### CODE REVIEW

**Comment by robinbraemer** [comment]
Thanks for your contribution!
What do you think about adding WritePacket instead?

**Comment by gmax79** [comment]
I don't think it's necessary now. Perhaps later you can do this if there are many types of Packet. Now the Player interface does not depend on the server version. Have you thought about the bot filter?

**Comment by robinbraemer** [comment]
Could you please explain the use-case, why it's useful to manually update the available commands for player?

**Comment by robinbraemer** [comment]
Could you please explain the use-case, why it's useful to manually update the available commands for player?

**Comment by gmax79** [comment]
If the players have a different set of commands. Commands change after entering a password for example. Otherwise you need to relogin.

**Comment by gmax79** [comment]
MR got a commit by mistake that adds a new parameter type to the command.

**Comment by robinbraemer** [comment]
Could you please split the second unrelated addition of the new parameter type in an own PR?

**Comment by gmax79** [comment]
i will create new pull separate requests

**Pull request closed without merging**
